#!/usr/bin/env bash
# Deploy birdblast AWS infra (worklog §18) end-to-end.
#   ./deploy.sh                # deploy core + cdn, upload SPA, print IDs
#   ./deploy.sh --spa-only     # just rebuild+upload the SPA + invalidate
#
# Requires: aws CLI, the `skimr` profile (account 872515289389), and the SPA built
# in ../web/dist (or ../web if it's plain static). Region us-east-1 (ACM/CloudFront).
set -euo pipefail

PROFILE=skimr
REGION=us-east-1
PROJECT=birdblast
DOMAIN=birdblast.the-edwards.fr
HOSTED_ZONE=Z03766021DZYFYQGYEP1J
CORE_STACK=${PROJECT}-core
CDN_STACK=${PROJECT}-cdn
HERE="$(cd "$(dirname "$0")" && pwd)"
AWS="aws --profile $PROFILE --region $REGION"

out() { $AWS cloudformation describe-stacks --stack-name "$1" \
        --query "Stacks[0].Outputs[?OutputKey=='$2'].OutputValue" --output text; }

deploy_core() {
  echo "==> Deploying core stack ($CORE_STACK)..."
  $AWS cloudformation deploy --stack-name "$CORE_STACK" \
    --template-file "$HERE/01-core.yaml" \
    --capabilities CAPABILITY_NAMED_IAM \
    --parameter-overrides ProjectName=$PROJECT ThingName=watergun-pi DomainName=$DOMAIN
}

deploy_cdn() {
  local web images
  web=$(out "$CORE_STACK" WebBucketName)
  images=$(out "$CORE_STACK" ImagesBucketName)
  echo "==> Deploying CDN stack ($CDN_STACK) [ACM validation can take a few min]..."
  $AWS cloudformation deploy --stack-name "$CDN_STACK" \
    --template-file "$HERE/02-cdn.yaml" \
    --parameter-overrides ProjectName=$PROJECT DomainName=$DOMAIN \
      HostedZoneId=$HOSTED_ZONE WebBucketName="$web" ImagesBucketName="$images"
}

upload_spa() {
  local web dist iot_data
  web=$(out "$CORE_STACK" WebBucketName)
  # Write the SPA runtime config from stack outputs.
  iot_data=$($AWS iot describe-endpoint --endpoint-type iot:Data-ATS --query endpointAddress --output text)
  mkdir -p "$HERE/../web"
  cat > "$HERE/../web/config.js" <<EOF
// Generated by infra/deploy.sh - do not edit by hand.
window.BIRDBLAST = {
  region: "$REGION",
  userPoolId: "$(out "$CORE_STACK" UserPoolId)",
  userPoolClientId: "$(out "$CORE_STACK" UserPoolClientId)",
  identityPoolId: "$(out "$CORE_STACK" IdentityPoolId)",
  hostedUiDomain: "$(out "$CORE_STACK" HostedUIDomain)",
  iotEndpoint: "$iot_data",
  imagesBucket: "$(out "$CORE_STACK" ImagesBucketName)",
  thingName: "watergun-pi",
  domain: "https://$DOMAIN"
};
EOF
  dist="$HERE/../web"
  [ -d "$HERE/../web/dist" ] && dist="$HERE/../web/dist"
  echo "==> Uploading SPA from $dist to s3://$web ..."
  $AWS s3 sync "$dist" "s3://$web/" --delete
  local distid
  distid=$(out "$CDN_STACK" DistributionId)
  echo "==> Invalidating CloudFront $distid ..."
  $AWS cloudfront create-invalidation --distribution-id "$distid" --paths "/*" >/dev/null
}

summary() {
  echo ""
  echo "======================= RECORD THESE IN worklog §18.6 (W7) ======================="
  echo "User Pool ID:        $(out "$CORE_STACK" UserPoolId)"
  echo "User Pool App Client:$(out "$CORE_STACK" UserPoolClientId)"
  echo "Identity Pool ID:    $(out "$CORE_STACK" IdentityPoolId)"
  echo "Hosted UI domain:    $(out "$CORE_STACK" HostedUIDomain)"
  echo "IoT endpoint (ATS):  $($AWS iot describe-endpoint --endpoint-type iot:Data-ATS --query endpointAddress --output text)"
  echo "IoT cred endpoint:   $($AWS iot describe-endpoint --endpoint-type iot:CredentialProvider --query endpointAddress --output text)"
  echo "S3 SPA bucket:       $(out "$CORE_STACK" WebBucketName)"
  echo "S3 images bucket:    $(out "$CORE_STACK" ImagesBucketName)"
  echo "Role alias:          $(out "$CORE_STACK" RoleAliasName)"
  echo "CloudFront dist ID:  $(out "$CDN_STACK" DistributionId)"
  echo "Site URL:            $(out "$CDN_STACK" SiteURL)"
  echo "=================================================================================="
}

if [ "${1:-}" = "--spa-only" ]; then
  upload_spa; summary; exit 0
fi
deploy_core
deploy_cdn
upload_spa
summary
echo "Next: ./provision-device-cert.sh  (creates + registers the Pi cert)"
echo "Then: create your Cognito user (see infra/README.md)."
